Add skeleton for cardano-wallet client, with admin status page for demo
chloekek/adatip pull request #38
Opened 2021-09-02 22:02 UTC by ruuda

## Summary

At some point we will need to integrate with `cardano-wallet` to interact with the blockchain.

 * Add a module for doing this, with one simple query for now.
 * Add an admin status page that displays the results of this query, more for demonstration purposes than anything else

## Details

`cardano-wallet` is written in Haskell and has a Servant API, including a client: https://github.com/input-output-hk/cardano-wallet/blob/3dd2989ab4e1d92f0add996c9e7152e2342d3729/lib/core/src/Cardano/Wallet/Api/Client.hs

However, depending on that library is a pain — it’s not published on Hackage, it uses its own bespoke build system, and it depends on `bech32` which is marked broken in Nixpkgs. I hoped for a moment that I could make it work by just copying the relevant files into our project, but it has enough dependencies that I felt this route was only going to result in misery.

So instead, define types with `FromJSON` instances ourselves, and then use `http-client`. It’s a lot more boilerplate, but it is easy to get it working and it sidesteps a lot of build and dependency problems. Also it allows us to continue using our own types.

For now there is only a function to query the `/network/information` endpoint, and I only parse a subset of the response. This is more of a proof of concept, with this in place it shouldn’t be too difficult to add other GET endpoints.

I split the `Cardano` module for this because I didn’t want to put all of it in one huge file.

2021-09-02 22:22 UTC, chloekek requested changes
Pretty nice. I also like the status page. There are some leftovers in the code:

2021-09-02 22:22 UTC, chloekek commented on adatipd/cabal.project.local
> +ignore-project: False
Missing license identifier.

2021-09-02 22:22 UTC, chloekek commented on adatipd/src/Adatipd/Cardano/Wallet.hs
> +  -> m a
Why is this generic over monad? It is only used in `makeRequest'` fixed at type `IO`.

2021-09-02 22:22 UTC, chloekek commented on adatipd/adatipd.cabal
> +        servant,
This isn’t listed in shell.nix. And I don’t think we need it.

2021-09-02 22:22 UTC, chloekek commented on adatipd/adatipd.cabal
> +        containers,
Also seems unused.

2021-09-02 22:22 UTC, chloekek commented on adatipd/adatipd.cabal
> +        unordered-containers,
Also seems unused.

2021-09-02 22:22 UTC, chloekek commented on adatipd/src/Adatipd/Cardano/Wallet.hs
> +module Adatipd.Cardano.Wallet
Would be nice to add documentation with some context about cardano-wallet and why we have our own module.

2021-09-03 19:12 UTC, ruuda commented on adatipd/cabal.project.local
> +ignore-project: False
Fixed.

2021-09-03 19:13 UTC, ruuda commented on adatipd/src/Adatipd/Cardano/Wallet.hs
> +  -> m a
I was playing around a bit with the types, at first I considered making a `MonadWallet` typeclass, but then I settled on just the concrete `WalletIO`. Will remove the premature generalization.

2021-09-03 19:14 UTC, ruuda commented on adatipd/adatipd.cabal
> +        servant,
This was a leftover from me trying to get `cardano-wallet`’s client to work. Removed now.

2021-09-03 19:15 UTC, ruuda commented on adatipd/adatipd.cabal
> +        containers,
Removed. I expect it to come back at some point though :sweat_smile:

2021-09-03 19:16 UTC, ruuda commented on adatipd/adatipd.cabal
> +        unordered-containers,
It was almost used, an `Aeson.Object` is a `HashMap Text Value`, and I briefly used `lookup`, but now it is no longer required. Removed.

2021-09-03 19:18 UTC, ruuda commented on adatipd/src/Adatipd/Cardano/Wallet.hs
> +module Adatipd.Cardano.Wallet
Added.

2021-09-03 19:30 UTC, ruuda commented
Also added a third schema example and a handler for it; apparently the network tip can be missing.

2021-09-03 19:33 UTC, chloekek approved these changes
:shipit:

2021-09-03 21:30 UTC, merged